# Generated by Django 2.2 on 2020-08-16 23:29

import django.core.files.storage
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestant', '0002_auto_20200731_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, storage=django.core.files.storage.FileSystemStorage(location='C:\\Users\\eblaze\\Desktop\\Projects\\paegent\\account/media'), upload_to='profile_images'),
        ),
    ]
