# Generated by Django 2.2 on 2020-08-19 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contestant', '0003_auto_20200817_0029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='image',
            field=models.ImageField(blank=True, upload_to='profile_images/'),
        ),
    ]
